name: Flat
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '10 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install webkit
          playwright install-deps webkit

      - name: Run TikTok RSS Generator
        run: python postprocessing.py
        env:
          MS_TOKEN: ${{ secrets.MS_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Latest TikTok RSS" || echo "No changes to commit"
          git push   
